### ISSUE TITLE
Editing articles after update to DokuWiki "Frusterick Manners" gives blank page as long as the notifier plugin is enabled

### ISSUE THREAD

**Issue by greldinard** [Fab-IT-ApS/dokuwiki-rocketchat-integration#1]
We recently updated to Frusterick Manners and moved to a new server. After this editing an article simply gives you a blank page. If the plugin is deactivated all is working fine.
Any ideas?
Any place were to look for more information?
Thanks in advance!

**Comment by greldinard** [comment]
Found some additional info in the Apache error log:

PHP Fatal error: 
Uncaught Error:
Call to undefined function curl_init() in /var/www/html/wiki/lib/plugins/rocketchatnotifier/action.php:81
Stack trace:
#0 /var/www/html/wiki/lib/plugins/rocketchatnotifier/action.php(26): action_plugin_rocketchatnotifier->handle()
#1 /var/www/html/wiki/inc/events.php(211): action_plugin_rocketchatnotifier->handle_action_act_preprocess(Object(Doku_Event), NULL)
#2 /var/www/html/wiki/inc/events.php(70): Doku_Event_Handler->process_event(Object(Doku_Event), 'BEFORE')
#3 /var/www/html/wiki/inc/actions.php(34): Doku_Event->advise_before()
#4 /var/www/html/wiki/doku.php(124): act_dispatch()
#5 {main} thrown in /var/www/html/wiki/lib/plugins/rocketchatnotifier/action.php on line 81, referer:
http://192.168.1.1/wiki/doku.php?id=spielwiese&do=edit

**Comment by greldinard** [comment]
Sorry. Found the error. Simply php-curl packet was not installed on new server. Would be nice to have it in the documentation as a requirement.

**Comment by cmol** [comment]
Hi @greldinard 
Sorry, I have missed this completely somehow! I'll add the dependency to the documentation. Thanks for letting me know.
