### ISSUE TITLE
works for Slack too

### ISSUE THREAD

**Issue by CvH** [Fab-IT-ApS/dokuwiki-rocketchat-integration#3]
Would it be possible to add "official" Slack support too - at least add it to the readme ?

As the original slack plugin is rather broken I tested this plugin and it works like a charm (just paste the slack webhook instead the rocketchat).

The needed output is the same for Rocketchat and Slack, maybe a good idea to merge it into one plugin ?

best regards

**Comment by cmol** [comment]
Wait, so the plugin I forked from for Slack, does not work with Slack, but this plugin does?
I can add a notice on it working for Slack as well on the readme, but I can't test it out currently.

Also, sorry for the long response time. I must have missed the email with the notification.

**Comment by CvH** [comment]
The original Slack plugin "works" but the output is broken, also there is no response from the author since "years" - so unlikely this get fixed.

As rocketchat and slack are basically the same and likely other services that uses this kind of webhook, so it would make sense to "merge" the plugins (I guess).

slack plugin vs rocketchat plugin (the yellow bg is due slack highlighting)
![image](https://user-images.githubusercontent.com/1355173/31573944-a16f4f04-b0c5-11e7-8982-476cebc0ed7a.png)

**Comment by cmol** [comment]
Looks good. I'll add a notice to the readme to start out with. I can try to write to the guy of the other repo I forked from, and see if he wants to redirect people to this repo.

**Comment by cmol** [comment]
I've added a notice on Slack in a44bb53. I'll try to contact the author of the original plugin. Thanks for the help.
